<?xml version="1.0" ?>

<!DOCTYPE htmlgrouplist [
	<!ELEMENT htmlgrouplist  (htmlgroup*)>
    <!ELEMENT htmlgroup      (htmlgrouptitle,htmltags)>
    <!ELEMENT htmlgrouptitle (#PCDATA)>
    <!ELEMENT htmltags       (htmltag*)>
    <!ELEMENT htmltag        (htmltagbegin,htmltagend,htmltaginfo,htmltagtitle,shortcut)>
    <!ELEMENT htmltagbegin   (#PCDATA)>
    <!ELEMENT htmltagend     (#PCDATA)>
    
    <!ELEMENT htmltaginfo    (#PCDATA)>
    <!ATTLIST htmltaginfo
    	lang	(de|en)		 #REQUIRED>
    
    <!ELEMENT htmltagtitle   (#PCDATA)>
    <!ELEMENT shortcut       (#PCDATA)>
]>

<htmlgrouplist>

	<htmlgroup>
	<htmlgrouptitle>Document</htmlgrouptitle>
	
	<htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;&#x21;DOCTYPE HTML PUBLIC &#x22;-&#x2F;&#x2F;W3C&#x2F;&#x2F;DTD HTML 2&#x2E;0&#x2F;&#x2F;EN&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">HTML 2&#x2E;0 Dokument</htmltaginfo>
		<htmltagtitle>HTML 2&#x2E;0</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;&#x21;DOCTYPE HTML PUBLIC &#x22;-&#x2F;&#x2F;W3C&#x2F;&#x2F;DTD HTML 3&#x2E;2&#x2F;&#x2F;EN&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>HTML 3&#x2E;2</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;&#x21;DOCTYPE HTML PUBLIC &#x22;-&#x2F;&#x2F;W3C&#x2F;&#x2F;DTD HTML 4&#x2E;0&#x2F;&#x2F;EN&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">HTML 4&#x2E;0 Dokument ohne mi&#xDF;billigte Tags</htmltaginfo>
		<htmltagtitle>HTML 4&#x2E;0</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;&#x21;DOCTYPE HTML PUBLIC &#x22;-&#x2F;&#x2F;W3C&#x2F;&#x2F;DTD HTML 4&#x2E;0 Transitional&#x2F;&#x2F;EN&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">HTML 4&#x2E;0 Dokument auch mit mi&#xDF;billigten Elementen</htmltaginfo>
		<htmltagtitle>HTML 4&#x2E;0 Trans&#x2E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;html&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;html&#x3E;</htmltagend>
		<htmltaginfo lang="de">Begrenzt ein HTML Dokument</htmltaginfo>
		<htmltagtitle>&#x3C;html&#x3E;&#x3C;&#x2F;html&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;head&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;head&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kopf des HTML-Dokumentes mit nur mittelbar sichtbaren Anweisungen&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;head&#x3E;&#x3C;&#x2F;head&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;title&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;title&#x3E;</htmltagend>
		<htmltaginfo lang="de">Der Titel des Dokumentes wird unter anderem in der Titelleiste des Browsers angezeigt&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;title&#x3E;&#x3C;&#x2F;title&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;body&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;body&#x3E;</htmltagend>
		<htmltaginfo lang="de">K&#xF6;rper des HTML-Dokumentes mit allen direkt sichtbaren Anweisungen&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;body&#x3E;&#x3C;&#x2F;body&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;a href&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;a&#x3E;</htmltagend>
		<htmltaginfo lang="de">Ein Hyperlink schafft Verbindungen &#x3A;-&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;a href&#x3D;&#x22;&#x22;&#x3E;&#x3C;&#x2F;a&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;a name&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Ein Anker definiert einen Zielpunkt f&#xFC;r einen Hyperlink</htmltaginfo>
		<htmltagtitle>&#x3C;a name&#x3D;&#x22;&#x22;&#x3E;&#x3C;&#x2F;a&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;link rel&#x3D;stylesheet type&#x3D;&#x22;text&#x2F;css&#x22; href&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Einbindung eines externen Stylesheets</htmltaginfo>
		<htmltagtitle>CSS-Datei</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;&#x21;--</htmltagbegin>
		<htmltagend>&#x2F;&#x2F;--&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kommentare bleiben unsichbar&#x2E; Auch Scripte und &#xE4;hnliches werden damit &#x22;versteckt&#x22;&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;&#x21;--Kommentar--&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;meta name&#x3D;&#x22;author&#x22; content&#x3D;&#x22;Thomas Weinert&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>&#x3C;meta name&#x3D;&#x22;author&#x22;&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Structure</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;div align&#x3D;&#x22;center&#x22;&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;div&#x3E;</htmltagend>
		<htmltaginfo lang="de">Ein Bereich mit Ausrichtung, kann auch als Ebene genutzt werden&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;div&#x3E;&#x3C;&#x2F;div&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;p&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;p&#x3E;</htmltagend>
		<htmltaginfo lang="de">Ein Absatz</htmltaginfo>
		<htmltagtitle>&#x3C;p&#x3E;&#x3C;&#x2F;p&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;span&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Ein Bereich ohne Ausrichtung&#x2E; Dient zum Anwenden von StyleSheets&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;span&#x3E;&#x3C;&#x2F;span&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;br&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Zeilenumbruch</htmltaginfo>
		<htmltagtitle>&#x3C;br&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;hr&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;nobr&#x3E;</htmltagend>
		<htmltaginfo lang="de">Horizontale Linie</htmltaginfo>
		<htmltagtitle>&#x3C;hr&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;nobr&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;nobr&#x3E;</htmltagend>
		<htmltaginfo lang="de">Definiert einen Bereich ohne automatischen Zeilenumbruch</htmltaginfo>
		<htmltagtitle>&#x3C;nobr&#x3E;&#x3C;&#x2F;nobr&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;wbr&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;wbr&#x3E;</htmltagend>
		<htmltaginfo lang="de">M&#xF6;glicher Zeilenumbruch innerhalb eine &#x3C;nobr&#x3E;-Bereiches</htmltaginfo>
		<htmltagtitle>&#x3C;wbr&#x3E;&#x3C;&#x2F;wbr&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;center&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;center&#x3E;</htmltagend>
		<htmltaginfo lang="de">Zentrierter Bereich&#x2E; Achtung  ab HTML 4&#x2E;0 mi&#xDF;billigt&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;center&#x3E;&#x3C;&#x2F;center&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Fonts</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;b&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;b&#x3E;</htmltagend>
		<htmltaginfo lang="de">Fette Schrift</htmltaginfo>
		<htmltagtitle>&#x3C;b&#x3E;&#x3C;&#x2F;b&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;i&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;i&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kursive Schrift</htmltaginfo>
		<htmltagtitle>&#x3C;i&#x3E;&#x3C;&#x2F;i&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;big&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;big&#x3E;</htmltagend>
		<htmltaginfo lang="de">Gr&#xF6;&#xDF;ere Schrift</htmltaginfo>
		<htmltagtitle>&#x3C;big&#x3E;&#x3C;&#x2F;big&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;small&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;small&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kleinere Schrift</htmltaginfo>
		<htmltagtitle>&#x3C;small&#x3E;&#x3C;&#x2F;small&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;strong&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;strong&#x3E;</htmltagend>
		<htmltaginfo lang="de">St&#xE4;rkere Schrift &#x28;meist fett&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;strong&#x3E;&#x3C;&#x2F;strong&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;s&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;s&#x3E;</htmltagend>
		<htmltaginfo lang="de">Durchgestrichener Text</htmltaginfo>
		<htmltagtitle>&#x3C;s&#x3E;&#x3C;&#x2F;s&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;strike&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;strike&#x3E;</htmltagend>
		<htmltaginfo lang="de">Durchgestrichener Text</htmltaginfo>
		<htmltagtitle>&#x3C;strike&#x3E;&#x3C;&#x2F;strike&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;sub&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;sub&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tiefgestellt</htmltaginfo>
		<htmltagtitle>&#x3C;sub&#x3E;&#x3C;&#x2F;sub&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;sup&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;sup&#x3E;</htmltagend>
		<htmltaginfo lang="de">Hochgestellt</htmltaginfo>
		<htmltagtitle>&#x3C;sup&#x3E;&#x3C;&#x2F;sup&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h1&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h1&#x3E;</htmltagend>
		<htmltaginfo lang="de">Sehr gro&#xDF;e &#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h1&#x3E;&#x3C;&#x2F;h1&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h2&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h2&#x3E;</htmltagend>
		<htmltaginfo lang="de">Gr&#xF6;&#xDF;ere &#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h2&#x3E;&#x3C;&#x2F;h2&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h3&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h3&#x3E;</htmltagend>
		<htmltaginfo lang="de">&#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h3&#x3E;&#x3C;&#x2F;h3&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h4&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h4&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kleinere &#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h4&#x3E;&#x3C;&#x2F;h4&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h5&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h5&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kleine &#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h5&#x3E;&#x3C;&#x2F;h5&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;h6&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;h6&#x3E;</htmltagend>
		<htmltaginfo lang="de">Sehr kleine &#xDC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;h6&#x3E;&#x3C;&#x2F;h6&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;tt&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;tt&#x3E;</htmltagend>
		<htmltaginfo lang="de">TeleType - Schreibmaschinenschrift</htmltaginfo>
		<htmltagtitle>&#x3C;tt&#x3E;&#x3C;&#x2F;tt&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;basefont&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Basisschriftart, -farbe und -gr&#xF6;&#xDF;e &#x28;in HTML 4 mi&#xDF;billigt&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;basefont&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;font&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;font&#x3E;</htmltagend>
		<htmltaginfo lang="de">Schriftart, -gr&#xF6;&#xDF;e oder -farbe &#xE4;ndern&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;font&#x3E;&#x3C;&#x2F;font&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Formatting</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;acronym&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;acronym&#x3E;</htmltagend>
		<htmltaginfo lang="de">Acronym</htmltaginfo>
		<htmltagtitle>&#x3C;acronym&#x3E;&#x3C;&#x2F;a&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;address&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;address&#x3E;</htmltagend>
		<htmltaginfo lang="de">Adresse</htmltaginfo>
		<htmltagtitle>&#x3C;address&#x3E;&#x3C;&#x2F;a&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;blockquote&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;blockquote&#x3E;</htmltagend>
		<htmltaginfo lang="de">Zitat</htmltaginfo>
		<htmltagtitle>&#x3C;blockquote&#x3E;&#x3C;&#x2F;b&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;cite&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;cite&#x3E;</htmltagend>
		<htmltaginfo lang="de">Literaturauszug</htmltaginfo>
		<htmltagtitle>&#x3C;cite&#x3E;&#x3C;&#x2F;cite&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;code&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;code&#x3E;</htmltagend>
		<htmltaginfo lang="de">Programmcode</htmltaginfo>
		<htmltagtitle>&#x3C;code&#x3E;&#x3C;&#x2F;code&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;del&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;del&#x3E;</htmltagend>
		<htmltaginfo lang="de">gel&#xF6;schter Text</htmltaginfo>
		<htmltagtitle>&#x3C;del&#x3E;&#x3C;&#x2F;del&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;em&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;em&#x3E;</htmltagend>
		<htmltaginfo lang="de">Hervorhebung</htmltaginfo>
		<htmltagtitle>&#x3C;em&#x3E;&#x3C;&#x2F;em&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;ins&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;ins&#x3E;</htmltagend>
		<htmltaginfo lang="de">Eingef&#xFC;gter Text</htmltaginfo>
		<htmltagtitle>&#x3C;ins&#x3E;&#x3C;&#x2F;ins&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;pre&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;pre&#x3E;</htmltagend>
		<htmltaginfo lang="de">Vorformatierter Text wird mit den Zeilenumbr&#xFC;chen und Leerzeichen im Quellcode ausgegeben&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;pre&#x3E;&#x3C;&#x2F;pre&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Lists</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;ul&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;ul&#x3E;</htmltagend>
		<htmltaginfo lang="de">ungeordnete Liste &#x28;Bulletliste&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;ul&#x3E;&#x3C;&#x2F;ul&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;ol&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;ol&#x3E;</htmltagend>
		<htmltaginfo lang="de">geordnete Liste &#x28;numerierte Liste&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;ol&#x3E;&#x3C;&#x2F;ol&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;li&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;li&#x3E;</htmltagend>
		<htmltaginfo lang="de">Listenelement</htmltaginfo>
		<htmltagtitle>&#x3C;li&#x3E;&#x3C;&#x2F;li&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;dl&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;dl&#x3E;</htmltagend>
		<htmltaginfo lang="de">Definitionliste</htmltaginfo>
		<htmltagtitle>&#x3C;dl&#x3E;&#x3C;&#x2F;dl&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;dt&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;dt&#x3E;</htmltagend>
		<htmltaginfo lang="de">Definitiontitel</htmltaginfo>
		<htmltagtitle>&#x3C;dt&#x3E;&#x3C;&#x2F;dt&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;dd&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;dd&#x3E;</htmltagend>
		<htmltaginfo lang="de">Definition</htmltaginfo>
		<htmltagtitle>&#x3C;dd&#x3E;&#x3C;&#x2F;dd&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;dir&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;dir&#x3E;</htmltagend>
		<htmltaginfo lang="de">Verzeichnisliste &#x28;in HTML 4 mi&#xDF;billigt&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;dir&#x3E;&#x3C;&#x2F;dir&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;menu&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;menu&#x3E;</htmltagend>
		<htmltaginfo lang="de">Men&#xFC;liste &#x28;in HTML 4 mi&#xDF;billigt&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;menu&#x3E;&#x3C;&#x2F;menu&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Tables</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;table&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;table&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabelle</htmltaginfo>
		<htmltagtitle>&#x3C;table&#x3E;&#x3C;&#x2F;table&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;thead&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;thead&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabellenkopf</htmltaginfo>
		<htmltagtitle>&#x3C;thead&#x3E;&#x3C;&#x2F;thead&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;tbody&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;tbody&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabellenk&#xF6;rper</htmltaginfo>
		<htmltagtitle>&#x3C;tbody&#x3E;&#x3C;&#x2F;tbody&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;tfoot&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;tfoot&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabellenfu&#xDF;</htmltaginfo>
		<htmltagtitle>&#x3C;tfoot&#x3E;&#x3C;&#x2F;tfoot&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;caption&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;caption&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabellen&#xFC;berschrift</htmltaginfo>
		<htmltagtitle>&#x3C;caption&#x3E;&#x3C;&#x2F;caption&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;colgroup&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;colgroup&#x3E;</htmltagend>
		<htmltaginfo lang="de">Spaltengruppe</htmltaginfo>
		<htmltagtitle>&#x3C;colgroup&#x3E;&#x3C;&#x2F;colgroup&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;col&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Spalte &#x28;f&#xFC;r Formatdefinitionen&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;col&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;tr&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;tr&#x3E;</htmltagend>
		<htmltaginfo lang="de">Tabellenzeile</htmltaginfo>
		<htmltagtitle>&#x3C;tr&#x3E;&#x3C;&#x2F;tr&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;th&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;th&#x3E;</htmltagend>
		<htmltaginfo lang="de">Kopfzelle</htmltaginfo>
		<htmltagtitle>&#x3C;th&#x3E;&#x3C;&#x2F;th&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;td&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;td&#x3E;</htmltagend>
		<htmltaginfo lang="de">Datenzelle</htmltaginfo>
		<htmltagtitle>&#x3C;td&#x3E;&#x3C;&#x2F;td&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Forms</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;form action&#x3D;&#x22;&#x22; method&#x3D;&#x22;POST&#x22;&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;form&#x3E;</htmltagend>
		<htmltaginfo lang="de">Formular</htmltaginfo>
		<htmltagtitle>&#x3C;form&#x3E;&#x3C;&#x2F;form&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">allgemeines Eingabefeld</htmltaginfo>
		<htmltagtitle>&#x3C;input&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;text&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Einzeiliges Texteingabefeld</htmltaginfo>
		<htmltagtitle>Textfeld</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;password&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Einzeiliges Texteingabefeld - die eingegebenen Zeichen werden maskiert &#x28;zB &#x2A;&#x29; dargestellt</htmltaginfo>
		<htmltagtitle>Passwort</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;radio&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Radiobutton &#x0D;&#x0A;Mehrere mit dem selben Namen &#x0D;&#x0A;ergeben eine Radiogroup&#x2E;</htmltaginfo>
		<htmltagtitle>Radiobutton</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;checkbox&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Checkbox</htmltaginfo>
		<htmltagtitle>Checkbox</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;submit&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Submit Button - l&#xF6;st die Formular-Aktion aus&#x2E;</htmltaginfo>
		<htmltagtitle>Submit</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;reset&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Button, welcher das Formular in den Ausganszustand versetzt&#x2E;</htmltaginfo>
		<htmltagtitle>Reset</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;image&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Ein Button als Bild&#x2E; Zus&#xE4;tzlich werden beim anklicken die Koordinaten &#x28;x,y&#x29; &#xFC;bermittelt</htmltaginfo>
		<htmltagtitle>Bild</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;hidden&#x22; name&#x3D;&#x22;&#x22; value&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Verstecktes Eingabefeld f&#xFC;r voreingestellte Werte</htmltaginfo>
		<htmltagtitle>Verborgen</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;input type&#x3D;&#x22;file&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Eingabefeld mit Dateiauswahlbutton &#x28;&#xD6;ffnen-Dialog&#x29;</htmltaginfo>
		<htmltagtitle>Dateiauswahl</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;textarea&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;textarea&#x3E;</htmltagend>
		<htmltaginfo lang="de">Mehrzeilige Eingabefeld</htmltaginfo>
		<htmltagtitle>Memofeld</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;select&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;select&#x3E;</htmltagend>
		<htmltaginfo lang="de">Auswahlliste - Combobox, Listbox</htmltaginfo>
		<htmltagtitle>Auswahlliste</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;option&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;option&#x3E;</htmltagend>
		<htmltaginfo lang="de">Eine Option der Auswahlliste</htmltaginfo>
		<htmltagtitle>Element</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;optgroup label&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;optgroup&#x3E;</htmltagend>
		<htmltaginfo lang="de">Schachtelung einer Auswahlliste &#x0D;&#x0A;wie in einem Men&#xFC;&#x2E; Wird weder&#x0D;&#x0A;von IE 4 noch von NN 4 unterst&#xFC;tzt&#x2E;</htmltaginfo>
		<htmltagtitle>Elementgruppe</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Frames</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;frameset border&#x3D;&#x22;0&#x22; frameborder&#x3D;&#x22;no&#x22; framespacing&#x3D;&#x22;0&#x22;&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;frameset&#x3E;</htmltagend>
		<htmltaginfo lang="de">Unterteilt das Browserfenster&#x2E; Jeder Teil kann wieder eine andere Datei anzeigen&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;frameset&#x3E;&#x3C;f&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;frame src&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Ein Rahmen f&#xFC;r ein Frameset</htmltaginfo>
		<htmltagtitle>&#x3C;frame&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;noframes&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;noframes&#x3E;</htmltagend>
		<htmltaginfo lang="de">Ein Bereich f&#xFC;r Browser, welche keine Framesets unterst&#xFC;tzen</htmltaginfo>
		<htmltagtitle>&#x3C;noframes&#x3E;&#x3C;n&#x2E;&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;iframe src&#x3D;&#x22;&#x22; width&#x3D;&#x22;&#x22; height&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Erzeugt in einer HTMLSeite einen Rahmen, in welchem andere Dateien angezeigt werden k&#xF6;nnen&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;iframe&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Media</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>&#x3C;marquee&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;marquee&#x3E;</htmltagend>
		<htmltaginfo lang="de">Erzeugt eine Laufschrifte, welche leider nur im MSIE funktioniert&#x2E;</htmltaginfo>
		<htmltagtitle>&#x3C;marquee&#x3E;&#x3C;m&#x2E;&#x2E;&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;img src&#x3D;&#x22;&#x22; border&#x3D;&#x22;&#x22; height&#x3D;&#x22;&#x22; width&#x3D;&#x22;&#x22;&#x3E;</htmltagbegin>
		<htmltagend></htmltagend>
		<htmltaginfo lang="de">Bildeinbindung</htmltaginfo>
		<htmltagtitle>&#x3C;img&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;applet&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;applet&#x3E;</htmltagend>
		<htmltaginfo lang="de">Einbindung eines JavaApplets</htmltaginfo>
		<htmltagtitle>&#x3C;applet&#x3E;&#x3C;&#x2F;applet&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>&#x3C;object&#x3E;</htmltagbegin>
		<htmltagend>&#x3C;&#x2F;object&#x3E;</htmltagend>
		<htmltaginfo lang="de">Einbindung einer externen Ressource &#x28;ActiveX, Video, etc&#x2E;&#x29;</htmltaginfo>
		<htmltagtitle>&#x3C;object&#x3E;&#x3C;&#x2F;object&#x3E;</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>
  </htmltags>
  </htmlgroup>

  
  <htmlgroup>
  <htmlgrouptitle>Events</htmlgrouptitle>
  
  <htmltags>
		<htmltag>
		<htmltagbegin>onload&#x3D;&#x22;</htmltagbegin>
		<htmltagend>&#x22;</htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>OnLoad</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>onunload&#x3D;&#x22;</htmltagbegin>
		<htmltagend>&#x22;</htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>OnUnLoad</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>onclick&#x3D;&#x22;</htmltagbegin>
		<htmltagend>&#x22;</htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>OnClick</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>
		<htmltagbegin>ondblclick&#x3D;&#x22;</htmltagbegin>
		<htmltagend>&#x22;</htmltagend>
		<htmltaginfo lang="de"></htmltaginfo>
		<htmltagtitle>OnDblClick</htmltagtitle>
		<shortcut>0</shortcut>
		</htmltag>

		<htmltag>