<?xml version="1.0" ?>

<!DOCTYPE tagdeflist [
    <!ELEMENT tagdeflist (tagdef*)>
    <!ELEMENT tagdef     (attributes,name)>
    <!ELEMENT attributes (#PCDATA)>
    <!ELEMENT name       (#PCDATA)>
]>

<!--

Todo: closing-flag
	  since HTML x.x attribute
	  vendor specific tags w vendor attribute
	  
-->

<tagdeflist>

	<tagdef>
		<attributes>href&#x3D;dialog&#x28;file&#x29;,target&#x3D;list&#x28;target&#x29;,name&#x3D;text,id&#x3D;text,type&#x3D;list&#x28;mimetype&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,class&#x3D;text,rel&#x3D;list&#x28;relation&#x29;,rev&#x3D;list&#x28;relation&#x29;,hreflang&#x3D;text,charset&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;</attributes>
		<name>a</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>acronym</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>address</name>
	</tagdef>

	<tagdef>
		<attributes>code&#x3D;dialog&#x28;file&#x29;,codebase&#x3D;text,archive&#x3D;dialog&#x28;file&#x29;,align&#x3D;list&#x28;imgalign&#x29;,width&#x3D;text,height&#x3D;text,hspace&#x3D;text,vspace&#x3D;text</attributes>
		<name>applet</name>
	</tagdef>

	<tagdef>
		<attributes>shape&#x3D;list&#x28;shape&#x29;,coords&#x3D;text,href&#x3D;dialog&#x28;file&#x29;,alt&#x3D;text,target&#x3D;list&#x28;target&#x29;</attributes>
		<name>area</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>b</name>
	</tagdef>

	<tagdef>
		<attributes>href&#x3D;text,target&#x3D;list&#x28;target&#x29;</attributes>
		<name>base</name>
	</tagdef>

	<tagdef>
		<attributes>size&#x3D;text,face&#x3D;dialog&#x28;font&#x29;,color&#x3D;dialog&#x28;color&#x29;</attributes>
		<name>basefont</name>
	</tagdef>

	<tagdef>
		<attributes>lang&#x3D;list&#x28;language&#x29;</attributes>
		<name>bdo</name>
	</tagdef>

	<tagdef>
		<attributes>loop&#x3D;text,src&#x3D;dialog&#x28;file&#x29;</attributes>
		<name>bgsound</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>big</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>blockquote</name>
	</tagdef>

	<tagdef>
		<attributes>clear&#x3D;list&#x28;clear&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,id&#x3D;text,class&#x3D;text</attributes>
		<name>br</name>
	</tagdef>

	<tagdef>
		<attributes>background&#x3D;dialog&#x28;file&#x29;,text&#x3D;dialog&#x28;color&#x29;,bgcolor&#x3D;dialog&#x28;color&#x29;,link&#x3D;dialog&#x28;color&#x29;,alink&#x3D;dialog&#x28;color&#x29;,vlink&#x3D;dialog&#x28;color&#x29;,bgproperties&#x3D;list&#x28;bgprop&#x29;,leftmargin&#x3D;text,topmargin&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>body</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,type&#x3D;text,value&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,accesskey&#x3D;text</attributes>
		<name>button</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;imgalign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>caption</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>center</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>cite</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>code</name>
	</tagdef>

	<tagdef>
		<attributes>width&#x3D;text,span&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,align&#x3D;list&#x28;colalign&#x29;,char&#x3D;text,charoff&#x3D;text</attributes>
		<name>col</name>
	</tagdef>

	<tagdef>
		<attributes>width&#x3D;text,span&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>colgroup</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>dd</name>
	</tagdef>

	<tagdef>
		<attributes>cite&#x3D;text,datetime&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>del</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>dfn</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>dir</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,name&#x3D;text,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>div</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>dl</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>dt</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>em</name>
	</tagdef>

	<tagdef>
		<attributes>src&#x3D;dialog&#x28;file&#x29;,width&#x3D;text,height&#x3D;text,autostart&#x3D;list&#x28;truefalse&#x29;,units&#x3D;list&#x28;units&#x29;,align&#x3D;list&#x28;imgalign&#x29;,border&#x3D;text,type&#x3D;list&#x28;mimetype&#x29;,pluginurl&#x3D;dialog&#x28;file&#x29;,pluginspage&#x3D;dialog&#x28;file&#x29;,hidden&#x3D;list&#x28;truefalse&#x29;,loop&#x3D;list&#x28;truefalse&#x29;,palette&#x3D;list&#x28;palette&#x29;,hspace&#x3D;text,vspace&#x3D;text</attributes>
		<name>embed</name>
	</tagdef>

	<tagdef>
		<attributes>color&#x3D;dialog&#x28;color&#x29;,size&#x3D;text,face&#x3D;dialog&#x28;font&#x29;</attributes>
		<name>font</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>fieldset</name>
	</tagdef>

	<tagdef>
		<attributes>action&#x3D;dialog&#x28;file&#x29;,method&#x3D;list&#x28;formmethod&#x29;,enctype&#x3D;list&#x28;mimetype&#x29;,name&#x3D;text,target&#x3D;list&#x28;target&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>form</name>
	</tagdef>

	<tagdef>
		<attributes>src&#x3D;dialog&#x28;file&#x29;,name&#x3D;text,scrolling&#x3D;list&#x28;yesnoauto&#x29;,marginwidth&#x3D;text,marginheight&#x3D;text,noresize&#x3D;boolean</attributes>
		<name>frame</name>
	</tagdef>

	<tagdef>
		<attributes>cols&#x3D;text,rows&#x3D;text,border&#x3D;text,frameborder&#x3D;list&#x28;yesno&#x29;,framespacing&#x3D;text,bordercolor&#x3D;dialog&#x28;color&#x29;</attributes>
		<name>frameset</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h1</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h2</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h3</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h4</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h5</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>h6</name>
	</tagdef>

	<tagdef>
		<attributes>profile&#x3D;dialog&#x28;file&#x29;,lang&#x3D;list&#x28;language&#x29;,dir&#x3D;list&#x28;rtlltr&#x29;</attributes>
		<name>head</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,width&#x3D;text,size&#x3D;text,noshade&#x3D;boolean,color&#x3D;dialog&#x28;color&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,id&#x3D;text,class&#x3D;text</attributes>
		<name>hr</name>
	</tagdef>

	<tagdef>
		<attributes>lang&#x3D;list&#x28;language&#x29;,dir&#x3D;list&#x28;rtlltr&#x29;</attributes>
		<name>html</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>i</name>
	</tagdef>

	<tagdef>
		<attributes>src&#x3D;dialog&#x28;file&#x29;,width&#x3D;text,height&#x3D;text,align&#x3D;list&#x28;halign&#x29;,hspace&#x3D;text,vspace&#x3D;text,scrolling&#x3D;list&#x28;yesnoauto&#x29;,noresize&#x3D;boolean</attributes>
		<name>iframe</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,top&#x3D;text,left&#x3D;text,width&#x3D;text,background&#x3D;dialog&#x28;file&#x29;,height&#x3D;text,pagex&#x3D;text,pagey&#x3D;text,clip&#x3D;text,bgcolor&#x3D;dialog&#x28;color&#x29;,z-index&#x3D;text,visibility&#x3D;list&#x28;visibility&#x29;</attributes>
		<name>ilayer</name>
	</tagdef>

	<tagdef>
		<attributes>src&#x3D;dialog&#x28;file&#x29;,alt&#x3D;text,height&#x3D;text,width&#x3D;text,border&#x3D;text,hspace&#x3D;text,vspace&#x3D;text,align&#x3D;list&#x28;imgalign&#x29;,name&#x3D;text,usemap&#x3D;text,dynsrc&#x3D;dialog&#x28;file&#x29;,loop&#x3D;text,start&#x3D;text,lowsrc&#x3D;dialog&#x28;file&#x29;,longdesc&#x3D;dialog&#x28;file&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>img</name>
	</tagdef>

	<tagdef>
		<attributes>type&#x3D;list&#x28;inputtype&#x29;,name&#x3D;text,value&#x3D;text,accept&#x3D;list&#x28;mimetype&#x29;,size&#x3D;text,maxlength&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,accesskey&#x3D;text,class&#x3D;text,src&#x3D;dialog&#x28;file&#x29;,alt&#x3D;text,height&#x3D;text,width&#x3D;text,border&#x3D;text,hspace&#x3D;text,vspace&#x3D;text,align&#x3D;list&#x28;imgalign&#x29;</attributes>
		<name>input</name>
	</tagdef>

	<tagdef>
		<attributes>cite&#x3D;text,datetime&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>ins</name>
	</tagdef>

	<tagdef>
		<attributes>prompt&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>isindex</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>kbd</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,accesskey&#x3D;text</attributes>
		<name>label</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,top&#x3D;text,left&#x3D;text,width&#x3D;text,background&#x3D;dialog&#x28;file&#x29;,height&#x3D;text,pagex&#x3D;text,pagey&#x3D;text,clip&#x3D;text,bgcolor&#x3D;dialog&#x28;color&#x29;,z-index&#x3D;text,visibility&#x3D;list&#x28;visibility&#x29;</attributes>
		<name>layer</name>
	</tagdef>

	<tagdef>
		<attributes>acceskey&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,accesskey&#x3D;text</attributes>
		<name>legend</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>li</name>
	</tagdef>

	<tagdef>
		<attributes>rel&#x3D;list&#x28;relation&#x29;,href&#x3D;dialog&#x28;file&#x29;,src&#x3D;dialog&#x28;file&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,media&#x3D;text</attributes>
		<name>link</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,name&#x3D;text</attributes>
		<name>map</name>
	</tagdef>

	<tagdef>
		<attributes>direction&#x3D;list&#x28;leftright&#x29;,scrollamount&#x3D;0,scrolldelay&#x3D;0,behavior&#x3D;list&#x28;behavior&#x29;,bgcolor&#x3D;dialog&#x28;color&#x29;,align&#x3D;list&#x28;imgalign&#x29;,height&#x3D;text,width&#x3D;text,hspace&#x3D;text,vspace&#x3D;text</attributes>
		<name>marquee</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>menu</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;list&#x28;metalist&#x29;,content&#x3D;text,http-equiv&#x3D;list&#x28;advmetalist&#x29;,lang&#x3D;list&#x28;language&#x29;,dir&#x3D;list&#x28;rtlltr&#x29;</attributes>
		<name>meta</name>
	</tagdef>

	<tagdef>
		<attributes>cols&#x3D;text,width&#x3D;text,gutter&#x3D;text</attributes>
		<name>multicol</name>
	</tagdef>

	<tagdef>
		<attributes>data&#x3D;dialog&#x28;file&#x29;,type&#x3D;list&#x28;mimetype&#x29;,align&#x3D;list&#x28;imgalign&#x29;,width&#x3D;text,height&#x3D;text,hspace&#x3D;text,vspace&#x3D;text,classid&#x3D;list&#x28;classid&#x29;,codebase&#x3D;text,codetype&#x3D;list&#x28;mimetype&#x29;,border&#x3D;text,name&#x3D;text,tabindex&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;text,class&#x3D;text</attributes>
		<name>object</name>
	</tagdef>

	<tagdef>
		<attributes>type&#x3D;list&#x28;oltype&#x29;,start&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>ol</name>
	</tagdef>

	<tagdef>
		<attributes>label&#x3D;text</attributes>
		<name>optgroup</name>
	</tagdef>

	<tagdef>
		<attributes>value&#x3D;text,label&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,selected&#x3D;boolean</attributes>
		<name>option</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;halign&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>p</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,value&#x3D;text</attributes>
		<name>param</name>
	</tagdef>

	<tagdef>
		<attributes>width&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>pre</name>
	</tagdef>

	<tagdef>
		<attributes>cite&#x3D;dialog&#x28;file&#x29;,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>q</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>s</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>samp</name>
	</tagdef>

	<tagdef>
		<attributes>language&#x3D;list&#x28;scriptlang&#x29;,src&#x3D;list&#x28;mimetype&#x29;</attributes>
		<name>script</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,size&#x3D;text,tabindex&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,accesskey&#x3D;text</attributes>
		<name>select</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>small</name>
	</tagdef>

	<tagdef>
		<attributes>type&#x3D;list&#x28;spacer&#x29;,size&#x3D;text,width&#x3D;text,height&#x3D;text,align&#x3D;list&#x28;leftright&#x29;</attributes>
		<name>spacer</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,name&#x3D;text,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>span</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>strike</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>strong</name>
	</tagdef>

	<tagdef>
		<attributes>lang&#x3D;list&#x28;language&#x29;,dir&#x3D;list&#x28;rtlltr&#x29;,type&#x3D;list&#x28;csslang&#x29;,media&#x3D;text</attributes>
		<name>style</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>sub</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>sup</name>
	</tagdef>

	<tagdef>
		<attributes>border&#x3D;text,cellpadding&#x3D;text,cellspacing&#x3D;text,align&#x3D;list&#x28;halign&#x29;,width&#x3D;text,height&#x3D;text,hspace&#x3D;text,vspace&#x3D;text,frame&#x3D;list&#x28;tableframe&#x29;,rules&#x3D;list&#x28;tablerules&#x29;,bgcolor&#x3D;dialog&#x28;color&#x29;,bordercolordark&#x3D;dialog&#x28;color&#x29;,bordercolorlight&#x3D;dialog&#x28;color&#x29;,background&#x3D;dialog&#x28;file&#x29;,summary&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>table</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>tbody</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;colalign&#x29;,valign&#x3D;list&#x28;valign&#x29;,colspan&#x3D;text,rowspan&#x3D;text,width&#x3D;text,height&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,bgcolor&#x3D;dialog&#x28;color&#x29;,background&#x3D;dialog&#x28;file&#x29;,abbr&#x3D;text,headers&#x3D;text,axis&#x3D;text,char&#x3D;text,charoff&#x3D;text,nowrap&#x3D;boolean</attributes>
		<name>td</name>
	</tagdef>

	<tagdef>
		<attributes>rows&#x3D;text,cols&#x3D;text,name&#x3D;text,warp&#x3D;list&#x28;warp&#x29;,accesskey&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>textarea</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>tfoot</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;colalign&#x29;,valign&#x3D;list&#x28;valign&#x29;,colspan&#x3D;text,rowspan&#x3D;text,width&#x3D;text,height&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,bgcolor&#x3D;dialog&#x28;color&#x29;,background&#x3D;dialog&#x28;file&#x29;,abbr&#x3D;text,scope&#x3D;list&#x28;scope&#x29;,axis&#x3D;text,char&#x3D;text,charoff&#x3D;text,nowrap&#x3D;boolean</attributes>
		<name>th</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>thead</name>
	</tagdef>

	<tagdef>
		<attributes>align&#x3D;list&#x28;colalign&#x29;,valign&#x3D;list&#x28;valign&#x29;,height&#x3D;text,name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,bgcolor&#x3D;dialog&#x28;color&#x29;,char&#x3D;text,charoff&#x3D;text</attributes>
		<name>tr</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>tt</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>u</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text,type&#x3D;list&#x28;ultype&#x29;</attributes>
		<name>ul</name>
	</tagdef>

	<tagdef>
		<attributes>name&#x3D;text,style&#x3D;dialog&#x28;css&#x29;,lang&#x3D;list&#x28;language&#x29;,id&#x3D;text,dir&#x3D;list&#x28;rtlltr&#x29;,class&#x3D;text</attributes>
		<name>var</name>
	</tagdef>

</tagdeflist>
